In [3]:
import pandas as pd
from sklearn.datasets import load_iris
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
print(df.head())


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


Implement a function that takes a dataset and returns the number of features and samples.


In [3]:
import pandas as pd
data = pd.read_csv("HousingData.csv")
features = data.columns.tolist()
print("Features of housing dataset: ", features)
print()
samples = data.head()
print("Samples of housing dataset: ", samples)


Features of housing dataset:  ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']

Samples of housing dataset:        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90    NaN  36.2  


 Split a dataset into training and testing sets with an 80/20 split.



In [19]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
data = load_iris()
df = pd.DataFrame(data=data.data, columns=data.feature_names)
df['target'] = data.target
X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set - Features shape:", X_train.shape, " Target shape:", y_train.shape)
print("Testing set - Features shape:", X_test.shape, " Target shape:", y_test.shape)

Training set - Features shape: (120, 4)  Target shape: (120,)
Testing set - Features shape: (30, 4)  Target shape: (30,)


Explore the basic statistics of a dataset, such as mean, median, and standard deviation for each feature.

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris

data = load_iris()
df = pd.DataFrame(data=data.data, columns=data.feature_names)

statistics = df.describe()

meanofFeatures = df.mean()
medianofFeatures= df.median()
stdDev = df.std()

print("Basic Statistics of Iris Dataset:")
print(statistics)
print("Mean of Features:")
print(meanofFeatures)
print("Median of Features:")
print(medianofFeatures)
print("Standard Deviation of Features:")
print(stdDev)

Visualize the distribution of one of the features in the dataset using a histogram.




In [ ]:
import pandas as pd

Write a Python script to create a list of 10 numbers and compute their mean.


In [7]:
import numpy as np
import random
randomNum = [random.randint(1,10) for _ in range(10)]
print(randomNum)
meanOfrandNum = np.mean(randomNum)
print("Mean of random number:", meanOfrandNum)

[10, 6, 3, 4, 8, 5, 5, 6, 1, 9]
Mean of random number: 5.7


Create a function that takes a list of numbers and returns a dictionary with the count, mean, median, and standard deviation.





In [9]:
import numpy as np

def retDic(list):
    dict = {}
    dict['count'] = len(list)
    dict['mean'] = np.mean(list)
    dict['median'] = np.median(list)
    dict['standard_deviation'] = np.std(list)
    
    return dict

list = [1, 2, 3, 4, 5, 6]
result = retDic(list)
print(result)

{'count': 6, 'mean': 3.5, 'median': 3.5, 'standard_deviation': 1.707825127659933}


Generate a 5x5 matrix of random numbers and print it.

In [10]:
import numpy as np
randMatrix = np.random.randint(1, 101, size=(5,5))
print("5x5 Matrix of randome numbers: ", randMatrix)

5x5 Matrix of randome numbers:  [[76 98 71 65 11]
 [37 81 18 90 29]
 [48 66 65 54 27]
 [55 97 41 55 75]
 [70 55 40 32 90]]


Load a CSV file into a Pandas DataFrame and print summary statistics for each column.



In [12]:
import pandas as pd
df =pd.read_csv("titanic.csv")
summaryStats = df.describe()
print("Summary statistics: ", summaryStats)

Summary statistics:         PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200  


 Implement a simple linear regression model using Scikit-Learn and print the model coefficients



In [18]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_csv("titanic.csv")
print(df.head())
print()

X = df[["Age"]].fillna(df["Age"].mean())
y = df[["Fare"]].fillna(df["Fare"].mean())

model = LinearRegression()
model.fit(X, y)
print("Coefficient (Age):", model.coef_[0])


   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  

C